### ISSUE TITLE
Poster image on hover disappear after deployment

### ISSUE THREAD

**Issue by thaomonster** [thaomonster/rancid-tomatillos#37]
**Describe the bug / point of concern**
After deploying the page when a mouse hover over a poster image the image disappears but when we hover over the title and freshness the image stays. 

**Location / Steps To Reproduce**
1. Go to https://rancid-tomatillos.vercel.app/
2. Hover over the poster image first and watch it disappear
3. Then hover over the title and freshness the image stays

**Screenshots**
<img src=https://media.giphy.com/media/eBbkHQPXCZJI0soexy/giphy.gif>

**Comment by deadbelly** [comment]
With @richardltyler 's help I found that the issues is that part of the styling- setting `.poster-img` to 80% opacity on hover- is getting changed to setting `.poster-img` to 1% opacity in the deployed version. Not sure why this is happening.

**Comment by deadbelly** [comment]
Found a possible solution [here](https://github.com/vercel/next.js/discussions/13069?sort_order=chronological). By setting opacity to 0.80 in `_poster.scss` instead of 80% the bug might resolve.

**Comment by deadbelly** [comment]
YAY IT WORKED
